#!/usr/bin/env python

import sys
import string
import pygraph
import csv

# Import pygraph
from pygraph.classes.graph import graph
from pygraph.classes.digraph import digraph
from pygraph.algorithms.searching import breadth_first_search
from pygraph.readwrite.dot import write
from pygraph.algorithms.minmax import shortest_path

# Graph creation
gr = graph()

# Add nodes and edges
data = open("borders.csv")
line = data.readline()
line = data.readline()
while line!= '':
    lineda=string.split(line,',')
    if lineda[0]!='':
        gr.add_node(lineda[0])
    line = data.readline()    
data = open("borders.csv")
line = data.readline()
line = data.readline()
while line!= '':
    lineda=string.split(line,',')
    borders = string.split(lineda[1],';')
    if lineda[1]!='\n':
        for f in borders:
            b = string.split(f,'*')
            check = 1
            if gr.edges() == []:
                gr.add_edge((lineda[0],b[0]))
                #gr.set_edge_weight((lineda[0],b[0]),wt=int(b[1]))
            for f in gr.edges():             
                test = lineda[0]+" "+b[0]
                s =string.join(f)
                if test == s:
                    check = 0
            if check != 0:
                gr.add_edge((lineda[0],b[0]))
                #gr.set_edge_weight((lineda[0],b[0]),wt=int(b[1]))
                check = 1
    line = data.readline()

#print gr
#for f in gr.edges():
#    print gr.edge_weight(f)

# Draw as PNG
'''
dot = write(gr, weighted=True)
f = open('edges.dot', 'w')
f.write(dot)
f.close()
import os
command = '"C:\\Program Files (x86)\\Graphviz 2.28\\bin\\dot.exe" -Tpng edges.dot > edges.png'
print command
os.system(command)
os.system('edges.png')
'''
#st, order = breadth_first_search(gr, root="United States")
st, order = shortest_path(gr,"United States")
with open("lengthsdata.csv", "wb") as f:
    csv.writer(f).writerows(order.iteritems())
gst = digraph()
gst.add_spanning_tree(st)
dot = write(gst, weighted=True)
f = open('edges2.dot', 'w')
f.write(dot)
f.close()


import os
command = '"C:\\Program Files (x86)\\Graphviz 2.28\\bin\\dot.exe" -Tpng edges2.dot > edges2.png'
print command
os.system(command)
os.system('edges2.png')

